spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.14.155:31000/cncp_biz?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: cncp_user
    password: 0xg&H|bu6hZTxRWmwQ.H
  elasticsearch:
    uris: http://elasticsearch-logging.cncp.com
    username: elastic
    password: DpyCx8hcTjBQ