server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /study-shiro
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 192.168.100.101
    port: 6379
    password:
    timeout: 6000ms # 连接超时时长
    jedis:
      pool:
        max-active: 1000 #连接池中最大连接数
        max-wait: -1ms # 连接池最大阻塞时间（使用负值表示没有限制）
        max-idle: 10 #连接池中最大空闲数量
        min-idle: 5 #连接池中最小空闲数量
  freemarker:
    suffix: .html
    request-context-attribute: request

szp:
  cluster: false #集群配置 true集群环境  false单机环境
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号隔开
  type-aliases-package: org.szpinc.study.shiro.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      # 主键类型，AUTO：数据库ID自增，INPUT：用户输入ID，ID_WORD:"全局唯一ID（数字类型唯一ID），UUID：＂全局唯一ID　UUID＂"
      id-type: auto
      # 字段策略 IGNORE: 忽略判断,NOT_NULL:非空判断
      field-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
